# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

aws_defaults: &aws_defaults
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

development:
  secret_key_base: 43a5df1c68d5c8ff9763cf434fc4ae8e3328918fc6d7081940d8cc268fbea7b48c070a3595b5310cb01301687601c98c2a4df994f20b6034f9575926ed9d6915
  aws:
    <<: *aws_defaults
    s3_bucket_name: <%= ENV["S3_BUCKET_NAME"] || "dev.files.fieldpapers.org" %>
    s3_bucket_region: <%= ENV["AWS_REGION"] || "us-east-1" %>

test:
  secret_key_base: 8250116f6fd746e5fc9258277e308b711c8e66e565cadb132a9911c7386e2253debd088c9c8d7b6c3455b205fad050e80cfb9a7c02c971bdf8439c654773fdcc
  aws:
    <<: *aws_defaults
    s3_bucket_name: "test.files.fieldpapers.org"
    s3_bucket_region: "us-east-1"

# Do not keep production secrets in the repository, instead read
# values from the environment.  NOTE: no AWS credentials here!
# Temporary EC2 credentials are used in production.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws:
    <<: *aws_defaults
    s3_bucket_name: <%= ENV["S3_BUCKET_NAME"] || "files.fieldpapers.org" %>
    s3_bucket_region: <%= ENV["AWS_REGION"] || "us-east-1" %>
